# Generated by Django 5.2.9 on 2025-12-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransactionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('category_name', models.CharField(max_length=100, null=True)),
                ('amount_direction', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vw_user_transactions',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
