# Generated by Django 5.2.9 on 2025-12-12 08:48

import django.db.models.deletion
import main.models
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bal', models.PositiveIntegerField(verbose_name='Денег на счету')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец карты')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=main.models.generate_number, unique=True, verbose_name='Номер карты')),
                ('CVV', models.PositiveIntegerField(default=main.models.generate_CVV, verbose_name='Код CVV')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата действия')),
                ('bal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.balance', verbose_name='Счёт')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.PositiveIntegerField(verbose_name='Лимит трат за месяц')),
                ('bal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.balance', verbose_name='Счёт')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Кол-во денег')),
                ('dir', models.BooleanField(verbose_name='Направление')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакции')),
                ('bal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.balance', verbose_name='Счёт')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='transactions',
            trigger=pgtrigger.compiler.Trigger(name='update_balance_on_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                    BEGIN\n                        IF NEW.dir THEN\n                            -- Если dir = True (доход), прибавляем деньги\n                            UPDATE main_balance \n                            SET bal = bal + NEW.amount \n                            WHERE id = NEW.bal_id;\n                        ELSE\n                            -- Если dir = False (расход), проверяем баланс и отнимаем деньги\n                            DECLARE\n                                current_balance INTEGER;\n                            BEGIN\n                                SELECT bal INTO current_balance \n                                FROM main_balance \n                                WHERE id = NEW.bal_id\n                                FOR UPDATE;\n                                \n                                IF current_balance >= NEW.amount THEN\n                                    UPDATE main_balance \n                                    SET bal = bal - NEW.amount \n                                    WHERE id = NEW.bal_id;\n                                ELSE\n                                    RAISE EXCEPTION 'Недостаточно средств на счету. Доступно: %, требуется: %', \n                                    current_balance, NEW.amount;\n                                END IF;\n                            END;\n                        END IF;\n                        RETURN NEW;\n                    END;\n                ", hash='9cda9d75ce2ff84b21999770991ba518ab5d89a1', operation='INSERT', pgid='pgtrigger_update_balance_on_insert_e76ab', table='main_transactions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='transactions',
            trigger=pgtrigger.compiler.Trigger(name='update_balance_on_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."bal_id" = (NEW."bal_id"))', func="\n                    BEGIN\n                        -- Сначала возвращаем старые деньги\n                        IF OLD.dir THEN\n                            -- Старая транзакция была доходом - отнимаем\n                            UPDATE main_balance \n                            SET bal = bal - OLD.amount \n                            WHERE id = OLD.bal_id;\n                        ELSE\n                            -- Старая транзакция была расходом - возвращаем\n                            UPDATE main_balance \n                            SET bal = bal + OLD.amount \n                            WHERE id = OLD.bal_id;\n                        END IF;\n                        \n                        -- Затем применяем новые значения\n                        IF NEW.dir THEN\n                            -- Новая транзакция - доход, прибавляем\n                            UPDATE main_balance \n                            SET bal = bal + NEW.amount \n                            WHERE id = NEW.bal_id;\n                        ELSE\n                            -- Новая транзакция - расход, проверяем баланс\n                            DECLARE\n                                current_balance INTEGER;\n                            BEGIN\n                                SELECT bal INTO current_balance \n                                FROM main_balance \n                                WHERE id = NEW.bal_id\n                                FOR UPDATE;\n                                \n                                IF current_balance >= NEW.amount THEN\n                                    UPDATE main_balance \n                                    SET bal = bal - NEW.amount \n                                    WHERE id = NEW.bal_id;\n                                ELSE\n                                    -- Возвращаем старые деньги обратно (откатываем первую операцию)\n                                    IF OLD.dir THEN\n                                        UPDATE main_balance \n                                        SET bal = bal + OLD.amount \n                                        WHERE id = OLD.bal_id;\n                                    ELSE\n                                        UPDATE main_balance \n                                        SET bal = bal - OLD.amount \n                                        WHERE id = OLD.bal_id;\n                                    END IF;\n                                    \n                                    RAISE EXCEPTION 'Недостаточно средств на счету после обновления. Требуется: %', \n                                    NEW.amount;\n                                END IF;\n                            END;\n                        END IF;\n                        RETURN NEW;\n                    END;\n                ", hash='e1b767414c00226d2998546e3a69d4207428a068', operation='UPDATE', pgid='pgtrigger_update_balance_on_update_856d1', table='main_transactions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='transactions',
            trigger=pgtrigger.compiler.Trigger(name='update_balance_on_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    BEGIN\n                        -- Возвращаем деньги при удалении транзакции\n                        IF OLD.dir THEN\n                            -- Удаляем доход - отнимаем деньги\n                            UPDATE main_balance \n                            SET bal = bal - OLD.amount \n                            WHERE id = OLD.bal_id;\n                        ELSE\n                            -- Удаляем расход - возвращаем деньги\n                            UPDATE main_balance \n                            SET bal = bal + OLD.amount \n                            WHERE id = OLD.bal_id;\n                        END IF;\n                        RETURN OLD;\n                    END;\n                ', hash='8beede0afa9678aa0031f50f5b1c91ab7c31d549', operation='DELETE', pgid='pgtrigger_update_balance_on_delete_64d52', table='main_transactions', when='BEFORE')),
        ),
    ]
