# Generated by Django 5.2.9 on 2025-12-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_balance_card_budget_transactions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'verbose_name': 'Баланс', 'verbose_name_plural': 'Балансы'},
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'Ограничение бюжета', 'verbose_name_plural': 'Ограничения бюжета'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Карта', 'verbose_name_plural': 'Карты'},
        ),
        migrations.AlterModelOptions(
            name='usertransactionview',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name': 'Статистика транзакций', 'verbose_name_plural': 'Статистика транзакций'},
        ),
    ]
